# Generated by Django 4.1.7 on 2023-05-10 08:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('applicant', models.CharField(max_length=50, verbose_name='Solicitante')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('client', models.CharField(max_length=50, verbose_name='Cliente')),
                ('product', models.TextField(verbose_name='Producto')),
                ('specifications', models.TextField(verbose_name='Especificaciones')),
                ('analysis', models.CharField(max_length=50, verbose_name='Análisis')),
                ('delivery_address', models.CharField(max_length=50, verbose_name='Dirección de entrega')),
                ('delivery_address_final', models.CharField(max_length=50, verbose_name='Dirección de entrega final')),
                ('client_data', models.TextField(verbose_name='Datos del cliente')),
                ('packaging_type', models.CharField(choices=[('E', 'Sobre'), ('B', 'Caja')], default='B', max_length=12,
                                                    verbose_name='Tipo de empaque')),
                ('market', models.CharField(choices=[('L', 'Local'), ('E', 'Exportación')], default='L', max_length=12,
                                            verbose_name='Mercado')),
                ('price',
                 models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('courier', models.CharField(max_length=50, verbose_name='Courier')),
                ('status', models.CharField(
                    choices=[('A', 'Solicitud recepcionada y validada'), ('DP', 'Entrega producción/calidad'),
                             ('WD', 'Entrega almacén'), ('ST', 'Enviado a Tarma'), ('RL', 'Recibido en Lima'),
                             ('SC', 'Programar courier'), ('STC', 'Enviado al cliente')], default='A', max_length=19,
                    verbose_name='Estado')),
                ('drive', models.URLField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSamples',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha de solicitud')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('applicant', models.CharField(max_length=50, verbose_name='Solicitante')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('client', models.CharField(max_length=50, verbose_name='Cliente')),
                ('product', models.TextField(verbose_name='Producto')),
                ('specifications', models.TextField(verbose_name='Especificaciones')),
                ('analysis', models.CharField(max_length=50, verbose_name='Análisis')),
                ('delivery_address', models.CharField(max_length=50, verbose_name='Dirección de entrega')),
                ('delivery_address_final', models.CharField(max_length=50, verbose_name='Dirección de entrega final')),
                ('client_data', models.TextField(verbose_name='Datos del cliente')),
                ('packaging_type', models.CharField(choices=[('E', 'Sobre'), ('B', 'Caja')], default='B', max_length=12,
                                                    verbose_name='Tipo de empaque')),
                ('market', models.CharField(choices=[('L', 'Local'), ('E', 'Exportación')], default='L', max_length=12,
                                            verbose_name='Mercado')),
                ('price',
                 models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('courier', models.CharField(max_length=50, verbose_name='Courier')),
                ('status', models.CharField(
                    choices=[('A', 'Solicitud recepcionada y validada'), ('DP', 'Entrega producción/calidad'),
                             ('WD', 'Entrega almacén'), ('ST', 'Enviado a Tarma'), ('RL', 'Recibido en Lima'),
                             ('SC', 'Programar courier'), ('STC', 'Enviado al cliente')], default='A', max_length=19,
                    verbose_name='Estado')),
                ('drive', models.URLField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Muestra',
                'verbose_name_plural': 'historical Muestras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
