/*AUTHENTICATION*/
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


/*COLLECTION*/
export const GET_PROVIDER_SUCCESS = 'GET_PROVIDER_SUCCESS';
export const GET_PROVIDERS_FAIL = 'GET_PROVIDERS_FAIL';
export const GET_PARCELS_SUCCESS = 'GET_PARCELS_SUCCESS';
export const GET_PARCELS_FAIL = 'GET_PARCELS_FAIL';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL';

export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';

export const UPDATE_PARCEL_SUCCESS = 'UPDATE_PARCEL_SUCCESS';
export const UPDATE_PARCEL_FAIL = 'UPDATE_PARCEL_FAIL';

export const ADD_PARCEL_SUCCESS = 'ADD_PARCEL_SUCCESS';
export const ADD_PARCEL_FAIL = 'ADD_PARCEL_FAIL';

export const GET_PROVIDERS_CATEGORY_SUCCESS = 'GET_PROVIDERS_CATEGORY_SUCCESS';
export const GET_PROVIDERS_CATEGORY_FAIL = 'GET_PROVIDERS_CATEGORY_FAIL';


//Management

export const LOADING_MANAGEMENT_SUCCESS = 'LOADING_MANAGEMENT_SUCCESS';
export const LOADING_MANAGEMENT_FAIL = 'LOADING_MANAGEMENT_FAIL';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL'
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL'


export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_FAIL = 'GET_SUPPLIERS_FAIL'
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';
export const GET_SUPPLIER_FAIL = 'GET_SUPPLIER_FAIL'
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAIL = 'DELETE_SUPPLIER_FAIL'
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAIL = 'UPDATE_SUPPLIER_FAIL'
export const GET_OUTSOURCINGS_SUCCESS = 'GET_OUTSOURCINGS_SUCCESS';
export const GET_OUTSOURCINGS_FAIL = 'GET_OUTSOURCINGS_FAIL'
export const GET_OUTSOURCING_SUCCESS = 'GET_OUTSOURCING_SUCCESS';
export const GET_OUTSOURCING_FAIL = 'GET_OUTSOURCING_FAIL'
export const DELETE_OUTSOURCING_SUCCESS = 'DELETE_OUTSOURCING_SUCCESS';
export const DELETE_OUTSOURCING_FAIL = 'DELETE_OUTSOURCING_FAIL'
export const UPDATE_OUTSOURCING_SUCCESS = 'UPDATE_OUTSOURCING_SUCCESS';
export const UPDATE_OUTSOURCING_FAIL = 'UPDATE_OUTSOURCING_FAIL'
export const GET_TRANSPORTS_SUCCESS = 'GET_TRANSPORTS_SUCCESS';
export const GET_TRANSPORTS_FAIL = 'GET_TRANSPORTS_FAIL'
export const GET_TRANSPORT_SUCCESS = 'GET_TRANSPORT_SUCCESS';
export const GET_TRANSPORT_FAIL = 'GET_TRANSPORT_FAIL'
export const DELETE_TRANSPORT_SUCCESS = 'DELETE_TRANSPORT_SUCCESS';
export const DELETE_TRANSPORT_FAIL = 'DELETE_TRANSPORT_FAIL'
export const UPDATE_TRANSPORT_SUCCESS = 'UPDATE_TRANSPORT_SUCCESS';
export const UPDATE_TRANSPORT_FAIL = 'UPDATE_TRANSPORT_FAIL'
export const GET_STORAGE_AREAS_SUCCESS = 'GET_STORAGE_AREAS_SUCCESS';
export const GET_STORAGE_AREAS_FAIL = 'GET_STORAGE_AREAS_FAIL'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL'
export const GET_COSTS_PRODUCTION_SUCCESS = 'GET_COSTS_PRODUCTION_SUCCESS';
export const GET_COSTS_PRODUCTION_FAIL = 'GET_COSTS_PRODUCTION_FAIL'
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCESS';
export const GET_UNITS_FAIL = 'GET_UNITS_FAIL'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'
export const GET_TAXES_SUCCESS = 'GET_TAXES_SUCCESS';
export const GET_TAXES_FAIL = 'GET_TAXES_FAIL'
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_FAIL = 'GET_CURRENCIES_FAIL'
export const GET_CONDITIONS_SUCCESS = 'GET_CONDITIONS_SUCCESS';
export const GET_CONDITIONS_FAIL = 'GET_CONDITIONS_FAIL'
export const GET_FAMILIES_SUCCESS = 'GET_FAMILIES_SUCCESS';
export const GET_FAMILIES_FAIL = 'GET_FAMILIES_FAIL'
export const GET_SUBFAMILIES_SUCCESS = 'GET_SUBFAMILIES_SUCCESS';
export const GET_SUBFAMILIES_FAIL = 'GET_SUBFAMILIES_FAIL'
export const GET_CUTS_SUCCESS = 'GET_CUTS_SUCCESS';
export const GET_CUTS_FAIL = 'GET_CUTS_FAIL'
export const GET_PACKINGS_SUCCESS = 'GET_PACKINGS_SUCCESS';
export const GET_PACKINGS_FAIL = 'GET_PACKINGS_FAIL'



/*LOGISTIC*/
export const GET_LOTS_STOCK_SUCCESS = 'GET_LOTS_STOCK_SUCCESS';
export const GET_LOTS_STOCK_FAIL = 'GET_LOTS_STOCK_FAIL';
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS';
export const GET_LOTS_FAIL = 'GET_LOTS_FAIL';

export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS';
export const GET_LOT_FAIL = 'GET_LOT_FAIL';

export const GET_PALLETS_SUCCESS = 'GET_PALLETS_SUCCESS';
export const GET_PALLETS_FAIL = 'GET_PALLETS_FAIL';

export const ADD_DATA_LOT_SUCCESS = 'ADD_DATA_LOT_SUCCESS';
export const ADD_DATA_LOT_FAIL = 'ADD_DATA_LOT_FAIL';

export const UPDATE_DATA_LOT_SUCCESS = 'UPDATE_DATA_LOT_SUCCESS';
export const UPDATE_DATA_LOT_FAIL = 'UPDATE_DATA_LOT_FAIL';

export const DELETE_DATA_LOT_SUCCESS = 'DELETE_DATA_LOT_SUCCESS';
export const DELETE_DATA_LOT_FAIL = 'DELETE_DATA_LOT_FAIL';

export const GET_DATA_LOT_SUCCESS = 'GET_DATA_LOT_SUCCESS';
export const GET_DATA_LOT_FAIL = 'GET_DATA_LOT_FAIL';

export const ADD_STOCK_LOT_SUCCESS = 'ADD_STOCK_LOT_SUCCESS';
export const ADD_STOCK_LOT_FAIL = 'ADD_STOCK_LOT_FAIL';

export const GET_STOCK_LOT_SUCCESS = 'GET_STOCK_LOT_SUCCESS';
export const GET_STOCK_LOT_FAIL = 'GET_STOCK_LOT_FAIL';

export const DELETE_STOCK_LOT_SUCCESS = 'DELETE_STOCK_LOT_SUCCESS';
export const DELETE_STOCK_LOT_FAIL = 'DELETE_STOCK_LOT_FAIL';


export const GET_MOTION_BOXES_SUCCESS = 'GET_MOTION_BOXES_SUCCESS';
export const GET_MOTION_BOXES_FAIL = 'GET_MOTION_BOXES_FAIL';

export const ADD_MOTION_BOX_SUCCESS = 'ADD_MOTION_BOX_SUCCESS';
export const ADD_MOTION_BOX_FAIL = 'ADD_MOTION_BOX_FAIL';

export const DELETE_MOTION_BOX_SUCCESS = 'DELETE_MOTION_BOX_SUCCESS';
export const DELETE_MOTION_BOX_FAIL = 'DELETE_MOTION_BOX_FAIL';


export const ADD_LOT_SUCCESS = 'ADD_LOT_SUCCESS';
export const ADD_LOT_FAIL = 'ADD_LOT_FAIL';


export const GET_OUTPUT_ITEMS_SUCCESS = 'GET_OUTPUT_ITEMS_SUCCESS';
export const GET_OUTPUT_ITEMS_FAIL = 'GET_OUTPUT_ITEMS_FAIL';

export const ADD_OUTPUT_ITEM_SUCCESS = 'ADD_OUTPUT_ITEM_SUCCESS';
export const ADD_OUTPUT_ITEM_FAIL = 'ADD_OUTPUT_ITEM_FAIL';


/*QUALITY ASSURANCE*/
export const GET_ANALYSIS_SUCCESS = 'GET_ANALYSIS_SUCCESS';
export const GET_ANALYSIS_FAIL = 'GET_ANALYSIS_FAIL';

export const UPDATE_ANALYSIS_SUCCESS = 'UPDATE_ANALYSIS_SUCCESS';
export const UPDATE_ANALYSIS_FAIL = 'UPDATE_ANALYSIS_FAIL';

/*SALES*/
export const GET_SAMPLES_SUCCESS = 'GET_SAMPLES_SUCCESS';
export const GET_SAMPLES_FAIL = 'GET_SAMPLES_FAIL';

export const ADD_SAMPLE_SUCCESS = 'ADD_SAMPLE_SUCCESS';
export const ADD_SAMPLE_FAIL = 'ADD_SAMPLE_FAIL';

export const UPDATE_SAMPLE_SUCCESS = 'UPDATE_SAMPLE_SUCCESS';
export const UPDATE_SAMPLE_FAIL = 'UPDATE_SAMPLE_FAIL';

export const GET_CALENDAR_SAMPLES_SUCCESS = 'GET_CALENDAR_SAMPLES_SUCCESS';
export const GET_CALENDAR_SAMPLES_FAIL = 'GET_CALENDAR_SAMPLES_FAIL';


// OPERATIONS
export const GET_RECORDS_MP_SUCCESS = 'GET_RECORDS_MP_SUCCESS';
export const GET_RECORDS_MP_FAIL = 'GET_RECORDS_MP_FAIL';

export const LOADING_RECORDS_MP_SUCCESS = 'LOADING_RECORDS_MP_SUCCESS';
export const LOADING_RECORDS_MP_FAIL = 'LOADING_RECORDS_MP_FAIL';

export const UPDATE_RECORD_MP_SUCCESS = 'UPDATE_RECORD_MP_SUCCESS';
export const UPDATE_RECORD_MP_FAIL = 'UPDATE_RECORD_MP_FAIL';


// PRODUCTION

export const GET_PROCESS_SUCCESS = 'GET_PROCESS_SUCCESS';
export const GET_PROCESS_FAIL = 'GET_PROCESS_FAIL';

export const UPDATE_PROCESS_SUCCESS = 'UPDATE_PROCESS_SUCCESS';
export const UPDATE_PROCESS_FAIL = 'UPDATE_PROCESS_FAIL';

export const GET_MOD_SUCCESS = 'GET_MOD_SUCCESS';
export const GET_MOD_FAIL = 'GET_MOD_FAIL';

export const UPDATE_MOD_SUCCESS = 'UPDATE_MOD_SUCCESS';
export const UPDATE_MOD_FAIL = 'UPDATE_MOD_FAIL';


// COSTS
export const GET_COSTS_SUCCESS = 'GET_COSTS_SUCCESS';
export const GET_COSTS_FAIL = 'GET_COSTS_FAIL';
export const UPDATE_COSTS_SUCCESS = 'UPDATE_COSTS_SUCCESS';
export const UPDATE_COSTS_FAIL = 'UPDATE_COSTS_FAIL';


