/*AUTHENTICATION*/
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


/*COLLECTION*/
export const GET_PROVIDER_SUCCESS = 'GET_PROVIDER_SUCCESS';
export const GET_PROVIDERS_FAIL = 'GET_PROVIDERS_FAIL';
export const GET_PARCELS_SUCCESS = 'GET_PARCELS_SUCCESS';
export const GET_PARCELS_FAIL = 'GET_PARCELS_FAIL';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL';

export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';

export const UPDATE_PARCEL_SUCCESS = 'UPDATE_PARCEL_SUCCESS';
export const UPDATE_PARCEL_FAIL = 'UPDATE_PARCEL_FAIL';

export const ADD_PARCEL_SUCCESS = 'ADD_PARCEL_SUCCESS';
export const ADD_PARCEL_FAIL = 'ADD_PARCEL_FAIL';

export const GET_PROVIDERS_CATEGORY_SUCCESS = 'GET_PROVIDERS_CATEGORY_SUCCESS';
export const GET_PROVIDERS_CATEGORY_FAIL = 'GET_PROVIDERS_CATEGORY_FAIL';
//Management
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL';
export const GET_MAQUILA_SUCCESS = 'GET_MAQUILA_SUCCESS';
export const GET_MAQUILA_FAIL = 'GET_MAQUILA_FAIL';
export const GET_PACKING_SUCCESS = 'GET_PACKING_SUCCESS';
export const GET_PACKING_FAIL = 'GET_PACKING_FAIL';
export const GET_TRANSPORT_SUCCESS = 'GET_TRANSPORT_SUCCESS';
export const GET_TRANSPORT_FAIL = 'GET_TRANSPORT_FAIL';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL';
export const GET_ZONES_SUCCESS = 'GET_ZONES_SUCCESS';
export const GET_ZONES_FAIL = 'GET_ZONES_FAIL';

/*LOGISTIC*/
export const GET_LOTS_STOCK_SUCCESS = 'GET_LOTS_STOCK_SUCCESS';
export const GET_LOTS_STOCK_FAIL = 'GET_LOTS_STOCK_FAIL';
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS';
export const GET_LOTS_FAIL = 'GET_LOTS_FAIL';

export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS';
export const GET_LOT_FAIL = 'GET_LOT_FAIL';

export const GET_PALLETS_SUCCESS = 'GET_PALLETS_SUCCESS';
export const GET_PALLETS_FAIL = 'GET_PALLETS_FAIL';

export const ADD_DATA_LOT_SUCCESS = 'ADD_DATA_LOT_SUCCESS';
export const ADD_DATA_LOT_FAIL = 'ADD_DATA_LOT_FAIL';

export const UPDATE_DATA_LOT_SUCCESS = 'UPDATE_DATA_LOT_SUCCESS';
export const UPDATE_DATA_LOT_FAIL = 'UPDATE_DATA_LOT_FAIL';

export const DELETE_DATA_LOT_SUCCESS = 'DELETE_DATA_LOT_SUCCESS';
export const DELETE_DATA_LOT_FAIL = 'DELETE_DATA_LOT_FAIL';

export const GET_DATA_LOT_SUCCESS = 'GET_DATA_LOT_SUCCESS';
export const GET_DATA_LOT_FAIL = 'GET_DATA_LOT_FAIL';

export const ADD_STOCK_LOT_SUCCESS = 'ADD_STOCK_LOT_SUCCESS';
export const ADD_STOCK_LOT_FAIL = 'ADD_STOCK_LOT_FAIL';

export const GET_STOCK_LOT_SUCCESS = 'GET_STOCK_LOT_SUCCESS';
export const GET_STOCK_LOT_FAIL = 'GET_STOCK_LOT_FAIL';

export const DELETE_STOCK_LOT_SUCCESS = 'DELETE_STOCK_LOT_SUCCESS';
export const DELETE_STOCK_LOT_FAIL = 'DELETE_STOCK_LOT_FAIL';


export const GET_MOTION_BOXES_SUCCESS = 'GET_MOTION_BOXES_SUCCESS';
export const GET_MOTION_BOXES_FAIL = 'GET_MOTION_BOXES_FAIL';

export const ADD_MOTION_BOX_SUCCESS = 'ADD_MOTION_BOX_SUCCESS';
export const ADD_MOTION_BOX_FAIL = 'ADD_MOTION_BOX_FAIL';

export const DELETE_MOTION_BOX_SUCCESS = 'DELETE_MOTION_BOX_SUCCESS';
export const DELETE_MOTION_BOX_FAIL = 'DELETE_MOTION_BOX_FAIL';


export const ADD_LOT_SUCCESS = 'ADD_LOT_SUCCESS';
export const ADD_LOT_FAIL = 'ADD_LOT_FAIL';


export const GET_OUTPUT_ITEMS_SUCCESS = 'GET_OUTPUT_ITEMS_SUCCESS';
export const GET_OUTPUT_ITEMS_FAIL = 'GET_OUTPUT_ITEMS_FAIL';

export const ADD_OUTPUT_ITEM_SUCCESS = 'ADD_OUTPUT_ITEM_SUCCESS';
export const ADD_OUTPUT_ITEM_FAIL = 'ADD_OUTPUT_ITEM_FAIL';


/*QUALITY ASSURANCE*/
export const GET_ANALYSIS_SUCCESS = 'GET_ANALYSIS_SUCCESS';
export const GET_ANALYSIS_FAIL = 'GET_ANALYSIS_FAIL';

export const UPDATE_ANALYSIS_SUCCESS = 'UPDATE_ANALYSIS_SUCCESS';
export const UPDATE_ANALYSIS_FAIL = 'UPDATE_ANALYSIS_FAIL';

/*SALES*/
export const GET_SAMPLES_SUCCESS = 'GET_SAMPLES_SUCCESS';
export const GET_SAMPLES_FAIL = 'GET_SAMPLES_FAIL';

export const ADD_SAMPLE_SUCCESS = 'ADD_SAMPLE_SUCCESS';
export const ADD_SAMPLE_FAIL = 'ADD_SAMPLE_FAIL';

export const UPDATE_SAMPLE_SUCCESS = 'UPDATE_SAMPLE_SUCCESS';
export const UPDATE_SAMPLE_FAIL = 'UPDATE_SAMPLE_FAIL';

export const GET_CALENDAR_SAMPLES_SUCCESS = 'GET_CALENDAR_SAMPLES_SUCCESS';
export const GET_CALENDAR_SAMPLES_FAIL = 'GET_CALENDAR_SAMPLES_FAIL';


// OPERATIONS
export const GET_RECORDS_MP_SUCCESS = 'GET_RECORDS_MP_SUCCESS';
export const GET_RECORDS_MP_FAIL = 'GET_RECORDS_MP_FAIL';

export const LOADING_RECORDS_MP_SUCCESS = 'LOADING_RECORDS_MP_SUCCESS';
export const LOADING_RECORDS_MP_FAIL = 'LOADING_RECORDS_MP_FAIL';

export const UPDATE_RECORD_MP_SUCCESS = 'UPDATE_RECORD_MP_SUCCESS';
export const UPDATE_RECORD_MP_FAIL = 'UPDATE_RECORD_MP_FAIL';

export const GET_KPI_SUCCESS = 'GET_KPI_SUCCESS';
export const GET_KPI_FAIL = 'GET_KPI_FAIL';


export const UPDATE_KPI_SUCCESS = 'UPDATE_KPI_SUCCESS';
export const UPDATE_KPI_FAIL = 'UPDATE_KPI_FAIL';



// INVENTORY

export const GET_MATERIALS_SUCCESS = 'GET_MATERIALS_SUCCESS';
export const GET_MATERIALS_FAIL = 'GET_MATERIALS_FAIL';

export const SYNC_MATERIALS_SUCCESS = 'SYNC_MATERIALS_SUCCESS';
export const SYNC_MATERIALS_FAIL = 'SYNC_MATERIALS_FAIL';
export const SET_SYNC_MATERIALS_LOADING = 'SET_SYNC_MATERIALS_LOADING';
export const REMOVE_SYNC_MATERIALS_LOADING = 'REMOVE_SYNC_MATERIALS_LOADING';

export const GET_PRODUCTS_KARDEX_SUCCESS = 'GET_PRODUCTS_KARDEX_SUCCESS';
export const GET_PRODUCTS_KARDEX_FAIL = 'GET_PRODUCTS_KARDEX_FAIL';


export const SYNC_PRODUCTS_KARDEX_SUCCESS = 'SYNC_PRODUCTS_KARDEX_SUCCESS';
export const SYNC_PRODUCTS_KARDEX_FAIL = 'SYNC_PRODUCTS_KARDEX_FAIL';

export const SET_SYNC_PRODUCTS_KARDEX_LOADING = 'SET_SYNC_PRODUCTS_KARDEX_LOADING';
export const REMOVE_SYNC_PRODUCTS_KARDEX_LOADING = 'REMOVE_SYNC_PRODUCTS_KARDEX_LOADING';

export const GET_SUMMARY_KARDEX_SUCCESS = 'GET_SUMMARY_KARDEX_SUCCESS';
export const GET_SUMMARY_KARDEX_FAIL = 'GET_SUMMARY_KARDEX_FAIL';

// PRODUCTION

export const GET_PROCESS_SUCCESS = 'GET_PROCESS_SUCCESS';
export const GET_PROCESS_FAIL = 'GET_PROCESS_FAIL';

export const UPDATE_PROCESS_SUCCESS = 'UPDATE_PROCESS_SUCCESS';
export const UPDATE_PROCESS_FAIL = 'UPDATE_PROCESS_FAIL';

export const GET_MOD_SUCCESS = 'GET_MOD_SUCCESS';
export const GET_MOD_FAIL = 'GET_MOD_FAIL';

export const UPDATE_MOD_SUCCESS = 'UPDATE_MOD_SUCCESS';
export const UPDATE_MOD_FAIL = 'UPDATE_MOD_FAIL';


// COSTS
export const GET_COSTS_SUCCESS = 'GET_COSTS_SUCCESS';
export const GET_COSTS_FAIL = 'GET_COSTS_FAIL';
export const UPDATE_COSTS_SUCCESS = 'UPDATE_COSTS_SUCCESS';
export const UPDATE_COSTS_FAIL = 'UPDATE_COSTS_FAIL';


