# Generated by Django 4.1.7 on 2023-06-27 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Precio')),
                ('information', models.TextField(blank=True, verbose_name='Información adicional')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('sap', models.CharField(max_length=10, verbose_name='Código SAP')),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cantidad mínima de pedido')),
                ('booked', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Reservado')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_group', to='management.categories', verbose_name='Grupo de producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_supplier', to='management.suppliers', verbose_name='Proveedor')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='management.categories', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Precio')),
                ('information', models.TextField(blank=True, verbose_name='Información adicional')),
                ('category', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='a', max_length=1, verbose_name='Categoría')),
                ('net_weight', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Peso neto envase')),
                ('performance', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='% Rendimiento')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.condition', verbose_name='Condición')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.cut', verbose_name='Corte')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.family', verbose_name='Familia')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_group', to='management.categories', verbose_name='Grupo de producto')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.packing', verbose_name='Empaque')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.product', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=15, verbose_name='ID del pedido')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la orden')),
                ('invoice_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='ID de la factura')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Fecha de llegada')),
                ('comment', models.TextField(blank=True, verbose_name='Información adicional')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Finalizado')], default='pending', max_length=20, verbose_name='Estado')),
                ('drive', models.URLField(verbose_name='Drive URL')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='StockExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de salida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_exits', to='operations_and_planning.material')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de ingreso')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='operations_and_planning.material')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15, verbose_name='Mes')),
                ('year', models.CharField(max_length=4, verbose_name='Año')),
                ('order_id', models.CharField(max_length=15, verbose_name='Orden de compra')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la orden')),
                ('quote_id', models.CharField(max_length=15, verbose_name='Proforma Invoice')),
                ('full_container_load_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre del contenedor')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cantidad')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio unitario')),
                ('market', models.CharField(choices=[('national', 'Nacional'), ('international', 'Internacional')], default='national', max_length=13, verbose_name='Mercado')),
                ('raw_material', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Materia Prima')),
                ('performance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Rendimiento')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Capacidad')),
                ('start_date', models.DateField(blank=True, verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(blank=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_date', models.DateField(blank=True, verbose_name='Fecha de envío')),
                ('etd', models.DateField(blank=True, verbose_name='Tiempo estimado de salida')),
                ('eta', models.DateField(blank=True, verbose_name='Tiempo estimado de salida')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Precio total')),
                ('management', models.CharField(choices=[('30', '30 %'), ('60', '60 %'), ('90', '90 %'), ('100', '100 %')], default='30', max_length=3)),
                ('delivery', models.CharField(choices=[('pending', 'Pendiente'), ('process', 'Proceso'), ('delivered', 'Enviado')], default='pending', max_length=9)),
                ('drive', models.URLField(verbose_name='Drive URL')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_customer', to='management.customer', verbose_name='Cliente')),
                ('process_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_process_plant', to='management.outsourcing', verbose_name='Planta de proceso')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_sku', to='operations_and_planning.product', verbose_name='SKU')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_tax', to='management.taxrates', verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'Orden de venta',
                'verbose_name_plural': 'Ordenes de venta',
                'ordering': ['-month', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_camp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Precio Campo')),
                ('freight', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9, null=True, verbose_name='Flete')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='logistic.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Registro Materia Prima',
                'verbose_name_plural': 'Registro de Materia Prima',
                'ordering': ['-lot__entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_materials', to='operations_and_planning.material', verbose_name='Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_products', to='operations_and_planning.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Recetario',
                'verbose_name_plural': 'Recetario',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio total')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_material', to='operations_and_planning.material', verbose_name='Material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_purchase', to='operations_and_planning.purchase', verbose_name='Orden de compra')),
            ],
            options={
                'verbose_name': 'Artículo de compra',
                'verbose_name_plural': 'Artículos de compra',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(related_name='purchases_items', through='operations_and_planning.PurchaseItems', to='operations_and_planning.material', verbose_name='Artículos'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_supplier', to='management.suppliers', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_tax', to='management.taxrates', verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(related_name='products_recipes', through='operations_and_planning.Recipe', to='operations_and_planning.material', verbose_name='Recetario'),
        ),
        migrations.AddField(
            model_name='product',
            name='subfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.subfamily', verbose_name='Sub Familia'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='management.categories', verbose_name='Unidad de medida'),
        ),
        migrations.CreateModel(
            name='HistoricalRecords',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price_camp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Precio Campo')),
                ('freight', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9, null=True, verbose_name='Flete')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistic.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'historical Registro Materia Prima',
                'verbose_name_plural': 'historical Registro de Materia Prima',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='operations_and_planning.material')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'unique_together': {('date', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('order_id', 'supplier')},
        ),
    ]
