# Generated by Django 4.1.7 on 2023-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregisteroutput',
            name='net_weight',
            field=models.FloatField(default=0, verbose_name='Kg Neto'),
        ),
        migrations.AddField(
            model_name='registeroutput',
            name='net_weight',
            field=models.FloatField(default=0, verbose_name='Kg Neto'),
        ),
    ]
