# Generated by Django 4.1.7 on 2023-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Codigo')),
                ('sap', models.CharField(blank=True, max_length=10, verbose_name='SAP')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('safety_stock', models.CharField(blank=True, max_length=100, verbose_name='Stock de Seguridad')),
                ('stock', models.CharField(blank=True, max_length=100, verbose_name='Stock')),
                ('cost', models.CharField(blank=True, max_length=100, verbose_name='Costo')),
                ('capacity', models.CharField(blank=True, max_length=100, verbose_name='Capacidad')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=100, verbose_name='Familia')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='Grupo')),
                ('certification', models.CharField(blank=True, max_length=100, verbose_name='Certificacion')),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='Producto')),
                ('cut', models.CharField(blank=True, max_length=100, verbose_name='Corte')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='Variedad')),
                ('client', models.CharField(blank=True, max_length=100, verbose_name='Cliente')),
                ('presentation', models.CharField(blank=True, max_length=100, verbose_name='Presentacion')),
                ('packaging', models.CharField(blank=True, max_length=100, verbose_name='Embalaje')),
                ('packing', models.CharField(blank=True, max_length=100, verbose_name='Empaque')),
                ('lot', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('date_of_production', models.CharField(blank=True, max_length=100, verbose_name='Fecha de Produccion')),
                ('date_of_expiration', models.CharField(blank=True, max_length=100, verbose_name='Fecha de Expiracion')),
                ('boxes', models.CharField(blank=True, max_length=100, verbose_name='Cajas')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Articulo')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='Proveedor')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Condicion')),
                ('fcl', models.CharField(blank=True, max_length=100, verbose_name='FCL')),
                ('campaign', models.CharField(blank=True, max_length=100, verbose_name='Campaña')),
                ('observations', models.CharField(blank=True, max_length=100, verbose_name='Observaciones')),
                ('stock', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9, verbose_name='Stock')),
                ('destines', models.CharField(blank=True, max_length=100, verbose_name='Destinos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['product'],
            },
        ),
    ]
