# Generated by Django 4.1.7 on 2023-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='management.contactpeople', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='outsourcing',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='management.contactpeople', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='management.contactpeople', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='management.contactpeople', verbose_name='Contacto'),
        ),
    ]
