# Generated by Django 4.1.7 on 2023-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_customer_contacts_alter_outsourcing_contacts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagearea',
            options={'ordering': ['name'], 'verbose_name': 'Zona de Almacenamiento', 'verbose_name_plural': 'Zonas de Almacenamiento'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='historicaloutsourcing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='historicalsuppliers',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='outsourcing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='transport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
