# Generated by Django 4.1.7 on 2023-06-27 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('enable', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('display_name', models.CharField(max_length=255, verbose_name='Mostrar nombre')),
                ('ruc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('contacts', models.ManyToManyField(to='management.contactpeople', verbose_name='Contacto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_provider', to='collection.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Área')),
                ('type_mp', models.CharField(choices=[('O', 'Orgánico'), ('C', 'Convencional')], default='C', max_length=100, verbose_name='Tipo de MP')),
                ('property_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Predio')),
                ('parcel', models.CharField(max_length=100, verbose_name='Parcela')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedad')),
                ('fosetyl', models.TextField(blank=True, max_length=200, null=True, verbose_name='Fosetyl')),
                ('pesticide', models.TextField(blank=True, max_length=200, null=True, verbose_name='Pesticida')),
                ('status', models.CharField(choices=[('P', 'Presencia'), ('C', 'Limpio')], default='P', max_length=100, verbose_name='Estado')),
                ('sample_type', models.CharField(choices=[('F', 'Fresco'), ('PT', 'Producto Terminado')], default='F', max_length=100, verbose_name='Tipo de Muestra')),
                ('observation', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('certifications', models.TextField(blank=True, default='Orgánico: \nBiosuisse: \nFairtrade: \n', max_length=200, null=True, verbose_name='Certificaciones')),
                ('clients', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clientes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('documents', models.URLField(blank=True, null=True, verbose_name='Drive')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['parcel'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProvider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('display_name', models.CharField(max_length=255, verbose_name='Mostrar nombre')),
                ('ruc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'historical Proveedor',
                'verbose_name_plural': 'historical Proveedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('enable', models.BooleanField(default=False, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParcel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Área')),
                ('type_mp', models.CharField(choices=[('O', 'Orgánico'), ('C', 'Convencional')], default='C', max_length=100, verbose_name='Tipo de MP')),
                ('property_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Predio')),
                ('parcel', models.CharField(max_length=100, verbose_name='Parcela')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedad')),
                ('fosetyl', models.TextField(blank=True, max_length=200, null=True, verbose_name='Fosetyl')),
                ('pesticide', models.TextField(blank=True, max_length=200, null=True, verbose_name='Pesticida')),
                ('status', models.CharField(choices=[('P', 'Presencia'), ('C', 'Limpio')], default='P', max_length=100, verbose_name='Estado')),
                ('sample_type', models.CharField(choices=[('F', 'Fresco'), ('PT', 'Producto Terminado')], default='F', max_length=100, verbose_name='Tipo de Muestra')),
                ('observation', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('certifications', models.TextField(blank=True, default='Orgánico: \nBiosuisse: \nFairtrade: \n', max_length=200, null=True, verbose_name='Certificaciones')),
                ('clients', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clientes')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('documents', models.URLField(blank=True, null=True, verbose_name='Drive')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'historical Parcela',
                'verbose_name_plural': 'historical Parcelas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
